
export default function TermsOfServicePage() {
  return (
    <div className="container mx-auto py-12">
      <h1 className="text-4xl md:text-5xl font-bold mb-8 font-headline text-primary">Terms of Service</h1>
      <div className="prose dark:prose-invert max-w-none lg:prose-lg">
        <p className="lead">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

        <p>Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the Scrapify web scraping chatbot tool (the "Service") operated by Scrapify ("us", "we", or "our").</p>

        <p>Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service. By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the terms then you may not access the Service.</p>

        <h2>1. Description of Service</h2>
        <p>Scrapify provides a web scraping tool that allows users to input URLs, extract data from web pages, and utilize AI-powered features for content summarization and classification. The data is primarily processed and stored on the client-side (user's browser) or sent to third-party AI services for processing as requested by the user.</p>

        <h2>2. User Responsibilities and Conduct</h2>
        <p>You agree to use Scrapify in compliance with all applicable local, state, national, and international laws, rules, and regulations. You shall not, shall not agree to, and shall not authorize or encourage any third party to:</p>
        <ul>
          <li>Use the Service to scrape or collect data from websites in a manner that violates their terms of service, privacy policies, or any applicable laws (including copyright and data protection laws).</li>
          <li>Use the Service for any illegal, unethical, or unauthorized purpose.</li>
          <li>Attempt to circumvent any rate limiting, IP blocking, or other anti-scraping measures implemented by target websites.</li>
          <li>Overload or disrupt the servers or networks of target websites or the Service itself.</li>
          <li>Scrape sensitive personal information, financial data, or other confidential information without proper authorization.</li>
          <li>Use the Service to infringe upon the intellectual property rights of others.</li>
          <li>Transmit any viruses, worms, defects, Trojan horses, or any items of a destructive nature.</li>
        </ul>
        <p>You are solely responsible for the URLs you choose to scrape and for ensuring that your use of the Service and the data obtained is lawful and ethical.</p>

        <h2>3. Intellectual Property</h2>
        <p>The Service and its original content (excluding content provided by users or scraped from third-party websites), features, and functionality are and will remain the exclusive property of Scrapify and its licensors. The Service is protected by copyright, trademark, and other laws of both the [Your Country/Jurisdiction] and foreign countries.</p>
        <p>Data scraped from third-party websites remains the property of its respective owners. Scrapify claims no ownership over content extracted from external websites.</p>

        <h2>4. AI-Powered Features</h2>
        <p>The Service utilizes third-party AI models (e.g., via Genkit and Google AI) for features like content summarization and classification. Your use of these features is subject to the terms and policies of these third-party AI providers. We are not responsible for the accuracy, completeness, or reliability of the output generated by these AI models.</p>
        
        <h2>5. Disclaimer of Warranties</h2>
        <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. Your use of the Service is at your sole risk. Scrapify expressly disclaims all warranties of any kind, whether express or implied, including, but not limited to, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement.</p>
        <p>Scrapify makes no warranty that (i) the Service will meet your requirements, (ii) the Service will be uninterrupted, timely, secure, or error-free, (iii) the results that may be obtained from the use of the Service will be accurate or reliable, or (iv) the quality of any products, services, information, or other material obtained by you through the Service will meet your expectations.</p>
        <p>Web scraping is inherently dependent on the structure and content of third-party websites, which can change without notice. We do not guarantee that the Service will be able to successfully scrape all websites or all types of data.</p>

        <h2>6. Limitation of Liability</h2>
        <p>In no event shall Scrapify, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service or on websites accessed via the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use, or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence), or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.</p>

        <h2>7. Indemnification</h2>
        <p>You agree to defend, indemnify, and hold harmless Scrapify and its licensee and licensors, and their employees, contractors, agents, officers, and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees), resulting from or arising out of a) your use and access of the Service, or b) a breach of these Terms, or c) your violation of any applicable laws or the rights of a third party (including, without limitation, any copyright, property, or privacy right).</p>

        <h2>8. Termination</h2>
        <p>We may terminate or suspend your access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.</p>
        <p>Upon termination, your right to use the Service will immediately cease. All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.</p>

        <h2>9. Governing Law</h2>
        <p>These Terms shall be governed and construed in accordance with the laws of [Your Country/Jurisdiction], without regard to its conflict of law provisions.</p>
        <p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.</p>

        <h2>10. Changes to Terms</h2>
        <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
        <p>By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, please stop using the Service.</p>

        <h2>11. Contact Us</h2>
        <p>If you have any questions about these Terms, please contact us at: <a href="mailto:terms@scrapify.example.com" className="text-primary hover:underline">terms@scrapify.example.com</a> (Note: This is a placeholder email).</p>
      </div>
    </div>
  );
}
